const fs = require("fs");
const path = require("path");

const arLocalePath = path.join(__dirname, "src", "locales", "ar.json");
const enLocalePath = path.join(__dirname, "src", "locales", "en.json");

const arLocales = JSON.parse(fs.readFileSync(arLocalePath, "utf8"));
const enLocales = JSON.parse(fs.readFileSync(enLocalePath, "utf8"));

function setNestedValue(obj, path, value) {
  const parts = path.split(".");
  let current = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!current[parts[i]]) current[parts[i]] = {};
    current = current[parts[i]];
  }
  current[parts[parts.length - 1]] = value;
}

const updates = [
  // AddTager.vue
  {
    key: "merchants.add_title",
    ar: "إضافة تاجر جديد",
    en: "Add New Merchant",
    file: "AddTager.vue",
    search: "إضافة تاجر جديد",
    replace: '{{ $t("merchants.add_title") }}',
  },
  {
    key: "merchants.basic_info",
    ar: "البيانات الأساسية",
    en: "Basic Information",
    file: "AddTager.vue",
    search: "البيانات الأساسية",
    replace: '{{ $t("merchants.basic_info") }}',
  },
  {
    key: "merchants.fullname",
    ar: "اسم التاجر بالكامل (الاسم الشخصي)",
    en: "Full Merchant Name",
    file: "AddTager.vue",
    search: 'label="اسم التاجر بالكامل (الاسم الشخصي)"',
    replace: ":label=\"$t('merchants.fullname')\"",
  },
  {
    key: "merchants.store_name",
    ar: "اسم المتجر / الشركة",
    en: "Store / Company Name",
    file: "AddTager.vue",
    search: 'label="اسم المتجر / الشركة"',
    replace: ":label=\"$t('merchants.store_name')\"",
  },
  {
    key: "merchants.phone",
    ar: "رقم التليفون",
    en: "Phone Number",
    file: "AddTager.vue",
    search: 'label="رقم التليفون"',
    replace: ":label=\"$t('merchants.phone')\"",
  },
  {
    key: "merchants.email",
    ar: "البريد الإلكتروني (لتسجيل الدخول)",
    en: "Email (For Login)",
    file: "AddTager.vue",
    search: 'label="البريد الإلكتروني (لتسجيل الدخول)"',
    replace: ":label=\"$t('merchants.email')\"",
  },
  {
    key: "merchants.password",
    ar: "كلمة المرور (دخول التاجر لحسابه)",
    en: "Password",
    file: "AddTager.vue",
    search: 'label="كلمة المرور (دخول التاجر لحسابه)"',
    replace: ":label=\"$t('merchants.password')\"",
  },
  {
    key: "merchants.business_info",
    ar: "بيانات النشاط التجاري",
    en: "Business Information",
    file: "AddTager.vue",
    search: "بيانات النشاط التجاري",
    replace: '{{ $t("merchants.business_info") }}',
  },
  {
    key: "merchants.category",
    ar: "تصنيف المتجر",
    en: "Store Category",
    file: "AddTager.vue",
    search: 'label="تصنيف المتجر"',
    replace: ":label=\"$t('merchants.category')\"",
  },
  {
    key: "merchants.tax_id",
    ar: "رقم البطاقة الضريبية",
    en: "Tax ID",
    file: "AddTager.vue",
    search: 'label="رقم البطاقة الضريبية"',
    replace: ":label=\"$t('merchants.tax_id')\"",
  },
  {
    key: "merchants.commercial_reg",
    ar: "رقم السجل التجاري",
    en: "Commercial Registration No.",
    file: "AddTager.vue",
    search: 'label="رقم السجل التجاري"',
    replace: ":label=\"$t('merchants.commercial_reg')\"",
  },
  {
    key: "merchants.address_info",
    ar: "العنوان والموقع",
    en: "Address & Location",
    file: "AddTager.vue",
    search: "العنوان والموقع",
    replace: '{{ $t("merchants.address_info") }}',
  },
  {
    key: "merchants.city",
    ar: "المحافظة / المدينة",
    en: "Governorate / City",
    file: "AddTager.vue",
    search: 'label="المحافظة / المدينة"',
    replace: ":label=\"$t('merchants.city')\"",
  },
  {
    key: "merchants.address_detail",
    ar: "العنوان بالتفصيل",
    en: "Detailed Address",
    file: "AddTager.vue",
    search: 'label="العنوان بالتفصيل"',
    replace: ":label=\"$t('merchants.address_detail')\"",
  },
  {
    key: "merchants.attachments",
    ar: "المرفقات والأوراق الرسمية",
    en: "Attachments & Official Docs",
    file: "AddTager.vue",
    search: "المرفقات والأوراق الرسمية",
    replace: '{{ $t("merchants.attachments") }}',
  },
  {
    key: "merchants.logo",
    ar: "شعار المتجر (Logo)",
    en: "Store Logo",
    file: "AddTager.vue",
    search: 'label="شعار المتجر (Logo)"',
    replace: ":label=\"$t('merchants.logo')\"",
  },
  {
    key: "merchants.docs_images",
    ar: "صور الأوراق (سجل/بطاقة)",
    en: "Document Images (Reg/ID)",
    file: "AddTager.vue",
    search: 'label="صور الأوراق (سجل/بطاقة)"',
    replace: ":label=\"$t('merchants.docs_images')\"",
  },
  {
    key: "merchants.clear_data",
    ar: "مسح البيانات",
    en: "Clear Data",
    file: "AddTager.vue",
    search: ">مسح البيانات</v-btn",
    replace: '>{{ $t("merchants.clear_data") }}</v-btn',
  },
  {
    key: "merchants.save",
    ar: "حفظ بيانات التاجر",
    en: "Save Merchant Data",
    file: "AddTager.vue",
    search: ">حفظ بيانات التاجر</v-btn",
    replace: '>{{ $t("merchants.save") }}</v-btn',
  },
  {
    key: "dashboard.close",
    ar: "إغلاق",
    en: "Close",
    file: "AddTager.vue",
    search: "إغلاق",
    replace: '{{ $t("dashboard.close") }}',
  },

  // AdvancedReportsPage.vue
  {
    key: "reports.main_title",
    ar: "مركز التقارير والتحليلات",
    en: "Reports & Analytics Center",
    file: "AdvancedReportsPage.vue",
    search:
      '{{ $t("dashboard.advanced_reports") || "مركز التقارير والتحليلات" }}',
    replace: '{{ $t("dashboard.advanced_reports") }}',
  },
  {
    key: "reports.subtitle",
    ar: "رؤية شاملة لأداء المتجر، المبيعات، والأرباح الحقيقية.",
    en: "Comprehensive view of store performance, sales, and real profits.",
    file: "AdvancedReportsPage.vue",
    search: "رؤية شاملة لأداء المتجر، المبيعات، والأرباح الحقيقية.",
    replace: '{{ $t("reports.subtitle") }}',
  },
  {
    key: "reports.days_7",
    ar: "7 أيام",
    en: "7 Days",
    file: "AdvancedReportsPage.vue",
    search: "7 أيام",
    replace: '{{ $t("reports.days_7") }}',
  },
  {
    key: "reports.days_30",
    ar: "30 يوم",
    en: "30 Days",
    file: "AdvancedReportsPage.vue",
    search: "30 يوم",
    replace: '{{ $t("reports.days_30") }}',
  },
  {
    key: "reports.days_90",
    ar: "90 يوم",
    en: "90 Days",
    file: "AdvancedReportsPage.vue",
    search: "90 يوم",
    replace: '{{ $t("reports.days_90") }}',
  },
  {
    key: "reports.revenue_trend",
    ar: "تحليل المبيعات (Revenue Trend)",
    en: "Sales Analysis (Revenue Trend)",
    file: "AdvancedReportsPage.vue",
    search: "تحليل المبيعات (Revenue Trend)",
    replace: '{{ $t("reports.revenue_trend") }}',
  },
  {
    key: "reports.live",
    ar: "مباشر",
    en: "Live",
    file: "AdvancedReportsPage.vue",
    search: "مباشر",
    replace: '{{ $t("reports.live") }}',
  },
  {
    key: "reports.sales_by_category",
    ar: "المبيعات حسب الفئات",
    en: "Sales By Category",
    file: "AdvancedReportsPage.vue",
    search: "المبيعات حسب الفئات",
    replace: '{{ $t("reports.sales_by_category") }}',
  },
  {
    key: "reports.top_products",
    ar: "المنتجات الأكثر مبيعاً",
    en: "Top Selling Products",
    file: "AdvancedReportsPage.vue",
    search: "المنتجات الأكثر مبيعاً",
    replace: '{{ $t("reports.top_products") }}',
  },
  {
    key: "reports.view_all",
    ar: "عرض الكل",
    en: "View All",
    file: "AdvancedReportsPage.vue",
    search: "عرض الكل",
    replace: '{{ $t("reports.view_all") }}',
  },

  // InventoryLogsPage.vue
  {
    key: "inventory.deleted_product",
    ar: "منتج محذوف",
    en: "Deleted Product",
    file: "InventoryLogsPage.vue",
    search: '|| "منتج محذوف"',
    replace: '|| $t("inventory.deleted_product")',
  },
  {
    key: "inventory.system_user",
    ar: "النظام",
    en: "System",
    file: "InventoryLogsPage.vue",
    search: '|| "النظام"',
    replace: '|| $t("inventory.system_user")',
  },

  // MangBanner.vue
  {
    key: "banners.title",
    ar: "إدارة البانرات والشرائح",
    en: "Manage Banners & Sliders",
    file: "MangBanner.vue",
    search: "إدارة البانرات والشرائح",
    replace: '{{ $t("banners.title") }}',
  },
  {
    key: "dashboard.deselect_all",
    ar: "إلغاء تحديد الكل",
    en: "Deselect All",
    file: "MangBanner.vue",
    search: '"إلغاء تحديد الكل"',
    replace: '$t("dashboard.deselect_all")',
  },
  {
    key: "dashboard.select_all",
    ar: "تحديد الكل",
    en: "Select All",
    file: "MangBanner.vue",
    search: '"تحديد الكل"',
    replace: '$t("dashboard.select_all")',
  },
  {
    key: "banners.type_label",
    ar: "نوع البانر",
    en: "Banner Type",
    file: "MangBanner.vue",
    search: 'label="نوع البانر"',
    replace: ":label=\"$t('banners.type_label')\"",
  },
  {
    key: "banners.add_new",
    ar: "إضافة بانر جديد",
    en: "Add New Banner",
    file: "MangBanner.vue",
    search: "إضافة بانر جديد",
    replace: '{{ $t("banners.add_new") }}',
  },
  {
    key: "banners.selected_count",
    ar: "تم تحديد {count} بانرات",
    en: "{count} Banners Selected",
    file: "MangBanner.vue",
    search: "تم تحديد {{ selectedIds.length }} بانرات",
    replace:
      '{{ $t("banners.selected_count").replace("{count}", selectedIds.length) }}',
  },
  {
    key: "dashboard.delete_selected",
    ar: "حذف المحدد",
    en: "Delete Selected",
    file: "MangBanner.vue",
    search: "حذف المحدد",
    replace: '{{ $t("dashboard.delete_selected") }}',
  },
  {
    key: "dashboard.cancel",
    ar: "إلغاء",
    en: "Cancel",
    file: "MangBanner.vue",
    search: ">إلغاء</v-btn",
    replace: '>{{ $t("dashboard.cancel") }}</v-btn',
  },

  // MangBlog.vue
  {
    key: "blog.title",
    ar: "إدارة المقالات",
    en: "Manage Articles",
    file: "MangBlog.vue",
    search: "إدارة المقالات",
    replace: '{{ $t("blog.title") }}',
  },
  {
    key: "blog.subtitle",
    ar: "تحكم في الأخبار والمقالات التي تظهر في صفحة المدونة الخاصة بمتجرك",
    en: "Control news and articles shown in your store blog",
    file: "MangBlog.vue",
    search: "تحكم في الأخبار والمقالات التي تظهر في صفحة المدونة الخاصة بمتجرك",
    replace: '{{ $t("blog.subtitle") }}',
  },
  {
    key: "blog.add_new",
    ar: "كتابة مقال جديد",
    en: "Write New Article",
    file: "MangBlog.vue",
    search: "كتابة مقال جديد",
    replace: '{{ $t("blog.add_new") }}',
  },
  {
    key: "blog.selected_count",
    ar: "تم تحديد {count} مقالات",
    en: "{count} Articles Selected",
    file: "MangBlog.vue",
    search: "تم تحديد {{ selectedIds.length }} مقالات",
    replace:
      '{{ $t("blog.selected_count").replace("{count}", selectedIds.length) }}',
  },
  {
    key: "dashboard.delete_selected",
    ar: "حذف المحدد",
    en: "Delete Selected",
    file: "MangBlog.vue",
    search: "حذف المحدد",
    replace: '{{ $t("dashboard.delete_selected") }}',
  },
  {
    key: "dashboard.cancel",
    ar: "إلغاء",
    en: "Cancel",
    file: "MangBlog.vue",
    search: ">إلغاء</v-btn",
    replace: '>{{ $t("dashboard.cancel") }}</v-btn',
  },

  // MangBrand.vue & MangCategoury.vue
  {
    key: "brands.main_title",
    ar: "الأقسام والماركات",
    en: "Categories & Brands",
    file: "MangBrand.vue",
    search: "الأقسام والماركات",
    replace: '{{ $t("brands.main_title") }}',
  },
  {
    key: "brands.add_cat",
    ar: "قسم",
    en: "Category",
    file: "MangBrand.vue",
    search: '"قسم"',
    replace: '$t("brands.add_cat")',
  },
  {
    key: "brands.add_brand",
    ar: "ماركة",
    en: "Brand",
    file: "MangBrand.vue",
    search: '"ماركة"',
    replace: '$t("brands.add_brand")',
  },
  {
    key: "brands.categories_tab",
    ar: "الأقسام (Categories)",
    en: "Categories",
    file: "MangBrand.vue",
    search: "الأقسام (Categories)",
    replace: '{{ $t("brands.categories_tab") }}',
  },
  {
    key: "brands.brands_tab",
    ar: "الماركات (Brands)",
    en: "Brands",
    file: "MangBrand.vue",
    search: "الماركات (Brands)",
    replace: '{{ $t("brands.brands_tab") }}',
  },
  {
    key: "brands.cat_img_th",
    ar: "صورة القسم",
    en: "Category Image",
    file: "MangBrand.vue",
    search: ">صورة القسم</th>",
    replace: '>{{ $t("brands.cat_img_th") }}</th>',
  },
  {
    key: "brands.cat_name_th",
    ar: "اسم القسم",
    en: "Category Name",
    file: "MangBrand.vue",
    search: ">اسم القسم</th>",
    replace: '>{{ $t("brands.cat_name_th") }}</th>',
  },
  {
    key: "brands.products_count_th",
    ar: "عدد المنتجات",
    en: "Products Count",
    file: "MangBrand.vue",
    search: ">عدد المنتجات</th>",
    replace: '>{{ $t("brands.products_count_th") }}</th>',
  },
  {
    key: "dashboard.status_th",
    ar: "الحالة",
    en: "Status",
    file: "MangBrand.vue",
    search: ">الحالة</th>",
    replace: '>{{ $t("dashboard.status_th") }}</th>',
  },
  {
    key: "dashboard.actions_th",
    ar: "الإجراءات",
    en: "Actions",
    file: "MangBrand.vue",
    search: ">الإجراءات</th>",
    replace: '>{{ $t("dashboard.actions_th") }}</th>',
  },
  {
    key: "brands.product_word",
    ar: "منتج",
    en: "Product",
    file: "MangBrand.vue",
    search: "منتج",
    replace: '{{ $t("brands.product_word") }}',
  },
  {
    key: "brands.brand_img_th",
    ar: "لوجو الماركة",
    en: "Brand Logo",
    file: "MangBrand.vue",
    search: ">لوجو الماركة</th>",
    replace: '>{{ $t("brands.brand_img_th") }}</th>',
  },
  {
    key: "brands.brand_name_th",
    ar: "اسم الماركة",
    en: "Brand Name",
    file: "MangBrand.vue",
    search: ">اسم الماركة</th>",
    replace: '>{{ $t("brands.brand_name_th") }}</th>',
  },
  {
    key: "dashboard.edit",
    ar: "تعديل",
    en: "Edit",
    file: "MangBrand.vue",
    search: '"تعديل"',
    replace: '$t("dashboard.edit")',
  },
  {
    key: "dashboard.add",
    ar: "إضافة",
    en: "Add",
    file: "MangBrand.vue",
    search: '"إضافة"',
    replace: '$t("dashboard.add")',
  },
  {
    key: "brands.cat_name_label",
    ar: "اسم القسم",
    en: "Category Name",
    file: "MangBrand.vue",
    search: "'اسم القسم'",
    replace: "$t('brands.cat_name_th')",
  },
  {
    key: "brands.brand_name_label",
    ar: "اسم الماركة",
    en: "Brand Name",
    file: "MangBrand.vue",
    search: "'اسم الماركة'",
    replace: "$t('brands.brand_name_th')",
  },
  {
    key: "dashboard.name_required",
    ar: "الاسم مطلوب",
    en: "Name is required",
    file: "MangBrand.vue",
    search: "'الاسم مطلوب'",
    replace: "$t('dashboard.name_required')",
  },
  {
    key: "brands.choose_cat_img",
    ar: "اختر صورة القسم",
    en: "Choose Category Image",
    file: "MangBrand.vue",
    search: "'اختر صورة القسم'",
    replace: "$t('brands.choose_cat_img')",
  },
  {
    key: "brands.choose_brand_img",
    ar: "اختر لوجو الماركة",
    en: "Choose Brand Logo",
    file: "MangBrand.vue",
    search: "'اختر لوجو الماركة'",
    replace: "$t('brands.choose_brand_img')",
  },
  {
    key: "dashboard.image_required",
    ar: "الصورة مطلوبة",
    en: "Image is required",
    file: "MangBrand.vue",
    search: "'الصورة مطلوبة'",
    replace: "$t('dashboard.image_required')",
  },
  {
    key: "dashboard.cancel",
    ar: "إلغاء",
    en: "Cancel",
    file: "MangBrand.vue",
    search: ">إلغاء</v-btn",
    replace: '>{{ $t("dashboard.cancel") }}</v-btn',
  },
  {
    key: "dashboard.save",
    ar: "حفظ",
    en: "Save",
    file: "MangBrand.vue",
    search: "حفظ",
    replace: '{{ $t("dashboard.save") }}',
  },
  {
    key: "dashboard.confirm_delete_q",
    ar: "هل أنت متأكد من حذف",
    en: "Are you sure you want to delete",
    file: "MangBrand.vue",
    search: "هل أنت متأكد من حذف",
    replace: '{{ $t("dashboard.confirm_delete_q") }}',
  },
  {
    key: "brands.this_cat",
    ar: "هذا القسم",
    en: "this category",
    file: "MangBrand.vue",
    search: '"هذا القسم"',
    replace: '$t("brands.this_cat")',
  },
  {
    key: "brands.this_brand",
    ar: "هذه الماركة",
    en: "this brand",
    file: "MangBrand.vue",
    search: '"هذه الماركة"',
    replace: '$t("brands.this_brand")',
  },
  {
    key: "dashboard.yes_delete",
    ar: "نعم، احذف",
    en: "Yes, Delete",
    file: "MangBrand.vue",
    search: ">نعم، احذف</v-btn",
    replace: '>{{ $t("dashboard.yes_delete") }}</v-btn',
  },
  {
    key: "dashboard.close",
    ar: "إغلاق",
    en: "Close",
    file: "MangBrand.vue",
    search: ">إغلاق</v-btn",
    replace: '>{{ $t("dashboard.close") }}</v-btn',
  },

  {
    key: "brands.main_title",
    ar: "الأقسام والماركات",
    en: "Categories & Brands",
    file: "MangCategoury.vue",
    search: "الأقسام والماركات",
    replace: '{{ $t("brands.main_title") }}',
  },
  {
    key: "brands.add_cat",
    ar: "قسم",
    en: "Category",
    file: "MangCategoury.vue",
    search: '"قسم"',
    replace: '$t("brands.add_cat")',
  },
  {
    key: "brands.add_brand",
    ar: "ماركة",
    en: "Brand",
    file: "MangCategoury.vue",
    search: '"ماركة"',
    replace: '$t("brands.add_brand")',
  },
  {
    key: "dashboard.cancel",
    ar: "إلغاء",
    en: "Cancel",
    file: "MangCategoury.vue",
    search: ">إلغاء</v-btn",
    replace: '>{{ $t("dashboard.cancel") }}</v-btn',
  },

  // MangUsers.vue
  {
    key: "users.title",
    ar: "إدارة العملاء",
    en: "Manage Customers",
    file: "MangUsers.vue",
    search: "إدارة العملاء",
    replace: '{{ $t("users.title") }}',
  },
  {
    key: "users.search_placeholder",
    ar: "ابحث بالاسم أو البريد الإلكتروني...",
    en: "Search by name or email...",
    file: "MangUsers.vue",
    search: 'label="ابحث بالاسم أو البريد الإلكتروني..."',
    replace: ":label=\"$t('users.search_placeholder')\"",
  },
  {
    key: "users.export_csv",
    ar: "تصدير (CSV)",
    en: "Export (CSV)",
    file: "MangUsers.vue",
    search: "تصدير (CSV)",
    replace: '{{ $t("users.export_csv") }}',
  },
  {
    key: "users.selected_count",
    ar: "تم تحديد {count} عملاء",
    en: "{count} Customers Selected",
    file: "MangUsers.vue",
    search: "تم تحديد {{ selectedIds.length }} عملاء",
    replace:
      '{{ $t("users.selected_count").replace("{count}", selectedIds.length) }}',
  },
  {
    key: "dashboard.delete_selected",
    ar: "حذف المحدد",
    en: "Delete Selected",
    file: "MangUsers.vue",
    search: "حذف المحدد",
    replace: '{{ $t("dashboard.delete_selected") }}',
  },
  {
    key: "dashboard.cancel",
    ar: "إلغاء",
    en: "Cancel",
    file: "MangUsers.vue",
    search: ">إلغاء</v-btn",
    replace: '>{{ $t("dashboard.cancel") }}</v-btn',
  },
  {
    key: "users.customer_th",
    ar: "العميل",
    en: "Customer",
    file: "MangUsers.vue",
    search: ">العميل</th>",
    replace: '>{{ $t("users.customer_th") }}</th>',
  },
  {
    key: "users.email_th",
    ar: "البريد الإلكتروني",
    en: "Email",
    file: "MangUsers.vue",
    search: ">البريد الإلكتروني</th>",
    replace: '>{{ $t("users.email_th") }}</th>',
  },
  {
    key: "users.join_date_th",
    ar: "تاريخ الانضمام",
    en: "Join Date",
    file: "MangUsers.vue",
    search: ">تاريخ الانضمام</th>",
    replace: '>{{ $t("users.join_date_th") }}</th>',
  },
  {
    key: "users.total_orders_th",
    ar: "إجمالي الطلبات",
    en: "Total Orders",
    file: "MangUsers.vue",
    search: ">إجمالي الطلبات</th>",
    replace: '>{{ $t("users.total_orders_th") }}</th>',
  },
  {
    key: "users.total_spent_th",
    ar: "إجمالي الإنفاق",
    en: "Total Spent",
    file: "MangUsers.vue",
    search: ">إجمالي الإنفاق</th>",
    replace: '>{{ $t("users.total_spent_th") }}</th>',
  },
  {
    key: "users.account_status_th",
    ar: "حالة الحساب",
    en: "Account Status",
    file: "MangUsers.vue",
    search: ">حالة الحساب</th>",
    replace: '>{{ $t("users.account_status_th") }}</th>',
  },
  {
    key: "dashboard.actions_th",
    ar: "الإجراءات",
    en: "Actions",
    file: "MangUsers.vue",
    search: ">الإجراءات</th>",
    replace: '>{{ $t("dashboard.actions_th") }}</th>',
  },
];

updates.forEach((item) => {
  setNestedValue(arLocales, item.key, item.ar);
  setNestedValue(enLocales, item.key, item.en);
});

fs.writeFileSync(arLocalePath, JSON.stringify(arLocales, null, 2), "utf8");
fs.writeFileSync(enLocalePath, JSON.stringify(enLocales, null, 2), "utf8");

const viewsDir = path.join(__dirname, "src", "views", "Dashboard");

// Perform replacements
updates.forEach((item) => {
  const filePath = path.join(viewsDir, item.file);
  if (fs.existsSync(filePath)) {
    let content = fs.readFileSync(filePath, "utf8");
    // Global replace
    content = content.split(item.search).join(item.replace);
    fs.writeFileSync(filePath, content, "utf8");
  }
});

console.log("Finished updating files and JSON.");
