export const themePalettes = [
  // 1-10: Classic & Corporate
  {
    id: 1,
    name: "Midnight Navy",
    primary: "#1e3a8a",
    secondary: "#1e40af",
    background: "#f8fafc",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#0f172a",
  },
  {
    id: 2,
    name: "Professional Blue",
    primary: "#2563eb",
    secondary: "#1d4ed8",
    background: "#f1f5f9",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1e293b",
  },
  {
    id: 3,
    name: "Slate Grey",
    primary: "#475569",
    secondary: "#334155",
    background: "#f8fafc",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#0f172a",
  },
  {
    id: 4,
    name: "Deep Charcoal",
    primary: "#1f2937",
    secondary: "#111827",
    background: "#f3f4f6",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#111827",
  },
  {
    id: 5,
    name: "Modern Silver",
    primary: "#64748b",
    secondary: "#475569",
    background: "#f1f5f9",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1e293b",
  },
  {
    id: 6,
    name: "Oxford Blue",
    primary: "#0f172a",
    secondary: "#1e293b",
    background: "#f8fafc",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#0f172a",
  },
  {
    id: 7,
    name: "Indigo Night",
    primary: "#312e81",
    secondary: "#3730a3",
    background: "#f5f3ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1e1b4b",
  },
  {
    id: 8,
    name: "Cobalt Blue",
    primary: "#2b6cb0",
    secondary: "#2c5282",
    background: "#ebf8ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1a365d",
  },
  {
    id: 9,
    name: "Steel",
    primary: "#718096",
    secondary: "#4a5568",
    background: "#edf2f7",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#2d3748",
  },
  {
    id: 10,
    name: "Charcoal Blue",
    primary: "#374151",
    secondary: "#1f2937",
    background: "#f9fafb",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#111827",
  },

  // 11-20: Nature & Eco
  {
    id: 11,
    name: "Forest Green",
    primary: "#065f46",
    secondary: "#047857",
    background: "#f0fdf4",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#064e3b",
  },
  {
    id: 12,
    name: "Emerald",
    primary: "#10b981",
    secondary: "#059669",
    background: "#ecfdf5",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#064e3b",
  },
  {
    id: 13,
    name: "Sage",
    primary: "#84cc16",
    secondary: "#65a30d",
    background: "#f7fee7",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1a2e05",
  },
  {
    id: 14,
    name: "Teal Dream",
    primary: "#0d9488",
    secondary: "#0f766e",
    background: "#f0fdfa",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#134e4a",
  },
  {
    id: 15,
    name: "Olive Garden",
    primary: "#3f6212",
    secondary: "#4d7c0f",
    background: "#f7fee7",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1a2e05",
  },
  {
    id: 16,
    name: "Leafy",
    primary: "#16a34a",
    secondary: "#15803d",
    background: "#f0fdf4",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#14532d",
  },
  {
    id: 17,
    name: "Seafoam",
    primary: "#2dd4bf",
    secondary: "#14b8a6",
    background: "#f0fdfa",
    surface: "#ffffff",
    onPrimary: "#111827",
    onSurface: "#134e4a",
  },
  {
    id: 18,
    name: "Pine",
    primary: "#14532d",
    secondary: "#166534",
    background: "#f0fdf4",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#052e16",
  },
  {
    id: 19,
    name: "Lime Punch",
    primary: "#a3e635",
    secondary: "#84cc16",
    background: "#f7fee7",
    surface: "#ffffff",
    onPrimary: "#111827",
    onSurface: "#1a2e05",
  },
  {
    id: 20,
    name: "Deep Teal",
    primary: "#134e4a",
    secondary: "#0f766e",
    background: "#f0fdfa",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#042f2e",
  },

  // 21-30: Luxury & Vibrant
  {
    id: 21,
    name: "Royal Purple",
    primary: "#7c3aed",
    secondary: "#6d28d9",
    background: "#f5f3ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1e1b4b",
  },
  {
    id: 22,
    name: "Elegant Gold",
    primary: "#d97706",
    secondary: "#b45309",
    background: "#fffbeb",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#451a03",
  },
  {
    id: 23,
    name: "Deep Crimson",
    primary: "#991b1b",
    secondary: "#7f1d1d",
    background: "#fef2f2",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#450a0a",
  },
  {
    id: 24,
    name: "Rose Pink",
    primary: "#db2777",
    secondary: "#be123c",
    background: "#fdf2f8",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#500724",
  },
  {
    id: 25,
    name: "Sunset Orange",
    primary: "#f97316",
    secondary: "#ea580c",
    background: "#fff7ed",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#431407",
  },
  {
    id: 26,
    name: "Magenta",
    primary: "#d0006f",
    secondary: "#9d0053",
    background: "#fff5f8",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#3d0020",
  },
  {
    id: 27,
    name: "Amethyst",
    primary: "#9333ea",
    secondary: "#7e22ce",
    background: "#faf5ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#2e1065",
  },
  {
    id: 28,
    name: "Goldenrod",
    primary: "#ca8a04",
    secondary: "#a16207",
    background: "#fefce8",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#422006",
  },
  {
    id: 29,
    name: "Ruby",
    primary: "#e11d48",
    secondary: "#be123c",
    background: "#fff1f2",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#4c0519",
  },
  {
    id: 30,
    name: "Plum",
    primary: "#6b21a8",
    secondary: "#581c87",
    background: "#f5f3ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#2e1065",
  },

  // 31-40: Modern Tech
  {
    id: 31,
    name: "Electric Cyan",
    primary: "#06b6d4",
    secondary: "#0891b2",
    background: "#ecfeff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#083344",
  },
  {
    id: 32,
    name: "Neon Blue",
    primary: "#3b82f6",
    secondary: "#2563eb",
    background: "#eff6ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#172554",
  },
  {
    id: 33,
    name: "Vivid Violet",
    primary: "#8b5cf6",
    secondary: "#7c3aed",
    background: "#f5f3ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1e1b4b",
  },
  {
    id: 34,
    name: "Sky Blue",
    primary: "#0ea5e9",
    secondary: "#0284c7",
    background: "#f0f9ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#0c4a6e",
  },
  {
    id: 35,
    name: "Minty Fresh",
    primary: "#2dd4bf",
    secondary: "#0d9488",
    background: "#f0fdfa",
    surface: "#ffffff",
    onPrimary: "#111827",
    onSurface: "#134e4a",
  },
  {
    id: 36,
    name: "Cyber Pink",
    primary: "#f43f5e",
    secondary: "#e11d48",
    background: "#fff1f2",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#4c0519",
  },
  {
    id: 37,
    name: "Dark Mode Tech",
    primary: "#10b981",
    secondary: "#059669",
    background: "#0f172a",
    surface: "#1e293b",
    onPrimary: "#ffffff",
    onSurface: "#f8fafc",
  },
  {
    id: 38,
    name: "Ultramarine",
    primary: "#4338ca",
    secondary: "#3730a3",
    background: "#eef2ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1e1b4b",
  },
  {
    id: 39,
    name: "Bright Aqua",
    primary: "#22d3ee",
    secondary: "#0891b2",
    background: "#ecfeff",
    surface: "#ffffff",
    onPrimary: "#111827",
    onSurface: "#083344",
  },
  {
    id: 40,
    name: "Soft Lilac",
    primary: "#a78bfa",
    secondary: "#8b5cf6",
    background: "#f5f3ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1e1b4b",
  },

  // 41-50: Earth & Friendly
  {
    id: 41,
    name: "Warm Amber",
    primary: "#f59e0b",
    secondary: "#d97706",
    background: "#fffbeb",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#451a03",
  },
  {
    id: 42,
    name: "Terracotta",
    primary: "#c2410c",
    secondary: "#9a3412",
    background: "#fff7ed",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#431407",
  },
  {
    id: 43,
    name: "Sandy",
    primary: "#ca8a04",
    secondary: "#854d0e",
    background: "#fefce8",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#3f2001",
  },
  {
    id: 44,
    name: "Chocolate",
    primary: "#78350f",
    secondary: "#451a03",
    background: "#fffbeb",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#2d1606",
  },
  {
    id: 45,
    name: "Caramel",
    primary: "#b45309",
    secondary: "#92400e",
    background: "#fff7ed",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#431407",
  },
  {
    id: 46,
    name: "Soft Peach",
    primary: "#fb923c",
    secondary: "#f97316",
    background: "#fff7ed",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#431407",
  },
  {
    id: 47,
    name: "Muted Clay",
    primary: "#94a3b8",
    secondary: "#64748b",
    background: "#f8fafc",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#0f172a",
  },
  {
    id: 48,
    name: "Dark Earth",
    primary: "#3f2b21",
    secondary: "#2c1d16",
    background: "#f7f3f1",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1a120d",
  },
  {
    id: 49,
    name: "Fresh Coral",
    primary: "#ff7f50",
    secondary: "#ff6347",
    background: "#fff5f2",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#3d1308",
  },
  {
    id: 50,
    name: "Slate Blue",
    primary: "#475569",
    secondary: "#1e293b",
    background: "#f1f5f9",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#0f172a",
  },

  // New 51-100 Palettes
  // 51-60: Pastel & Soft
  {
    id: 51,
    name: "Soft Sky",
    primary: "#bae6fd",
    secondary: "#7dd3fc",
    background: "#f0f9ff",
    surface: "#ffffff",
    onPrimary: "#0c4a6e",
    onSurface: "#0c4a6e",
  },
  {
    id: 52,
    name: "Lavender Mist",
    primary: "#e9d5ff",
    secondary: "#d8b4fe",
    background: "#faf5ff",
    surface: "#ffffff",
    onPrimary: "#581c87",
    onSurface: "#581c87",
  },
  {
    id: 53,
    name: "Mint Foam",
    primary: "#99f6e4",
    secondary: "#5eead4",
    background: "#f0fdfa",
    surface: "#ffffff",
    onPrimary: "#134e4a",
    onSurface: "#134e4a",
  },
  {
    id: 54,
    name: "Peach Fuzz",
    primary: "#ffedd5",
    secondary: "#fed7aa",
    background: "#fff7ed",
    surface: "#ffffff",
    onPrimary: "#9a3412",
    onSurface: "#9a3412",
  },
  {
    id: 55,
    name: "Rose Quartz",
    primary: "#fce7f3",
    secondary: "#fbcfe8",
    background: "#fdf2f8",
    surface: "#ffffff",
    onPrimary: "#9d174d",
    onSurface: "#9d174d",
  },
  {
    id: 56,
    name: "Lemon Chiffon",
    primary: "#fef9c3",
    secondary: "#fef08a",
    background: "#fefce8",
    surface: "#ffffff",
    onPrimary: "#854d0e",
    onSurface: "#854d0e",
  },
  {
    id: 57,
    name: "Ice Breeze",
    primary: "#cffafe",
    secondary: "#a5f3fc",
    background: "#f0f9ff",
    surface: "#ffffff",
    onPrimary: "#0e7490",
    onSurface: "#0e7490",
  },
  {
    id: 58,
    name: "Spring Bud",
    primary: "#ecfccb",
    secondary: "#d9f99d",
    background: "#f7fee7",
    surface: "#ffffff",
    onPrimary: "#3f6212",
    onSurface: "#3f6212",
  },
  {
    id: 59,
    name: "Cotton Candy",
    primary: "#fae8ff",
    secondary: "#f5d0fe",
    background: "#fdf4ff",
    surface: "#ffffff",
    onPrimary: "#701a75",
    onSurface: "#701a75",
  },
  {
    id: 60,
    name: "Baby Blue",
    primary: "#dbeafe",
    secondary: "#bfdbfe",
    background: "#eff6ff",
    surface: "#ffffff",
    onPrimary: "#1e40af",
    onSurface: "#1e40af",
  },

  // 61-70: Vintage & Retro
  {
    id: 61,
    name: "Retro Mustard",
    primary: "#fbbf24",
    secondary: "#f59e0b",
    background: "#fffbeb",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#451a03",
  },
  {
    id: 62,
    name: "Vintage Teal",
    primary: "#14b8a6",
    secondary: "#0d9488",
    background: "#f0fdfa",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#134e4a",
  },
  {
    id: 63,
    name: "Old Brick",
    primary: "#b91c1c",
    secondary: "#991b1b",
    background: "#fef2f2",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#450a0a",
  },
  {
    id: 64,
    name: "Muted Moss",
    primary: "#65a30d",
    secondary: "#4d7c0f",
    background: "#f7fee7",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1a2e05",
  },
  {
    id: 65,
    name: "Dusty Rose",
    primary: "#e879f9",
    secondary: "#d946ef",
    background: "#fdf4ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#701a75",
  },
  {
    id: 66,
    name: "Antique Gold",
    primary: "#d97706",
    secondary: "#b45309",
    background: "#fffbeb",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#451a03",
  },
  {
    id: 67,
    name: "Retro Navy",
    primary: "#1e3a8a",
    secondary: "#1e40af",
    background: "#f8fafc",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#0f172a",
  },
  {
    id: 68,
    name: "Salmon Retro",
    primary: "#f87171",
    secondary: "#ef4444",
    background: "#fef2f2",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#7f1d1d",
  },
  {
    id: 69,
    name: "Burnt Sienna",
    primary: "#9a3412",
    secondary: "#7c2d12",
    background: "#fff7ed",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#431407",
  },
  {
    id: 70,
    name: "Sepia Tone",
    primary: "#78350f",
    secondary: "#451a03",
    background: "#fffbeb",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#2d1606",
  },

  // 71-80: Industrial & Metal
  {
    id: 71,
    name: "Gunmetal",
    primary: "#2d3748",
    secondary: "#1a202c",
    background: "#f7fafc",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1a202c",
  },
  {
    id: 72,
    name: "Brushed Nickel",
    primary: "#718096",
    secondary: "#4a5568",
    background: "#edf2f7",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#2d3748",
  },
  {
    id: 73,
    name: "Rust",
    primary: "#9c4221",
    secondary: "#7b341e",
    background: "#fffaf0",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#2d3748",
  },
  {
    id: 74,
    name: "Steel Blue",
    primary: "#4a5568",
    secondary: "#2d3748",
    background: "#f7fafc",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1a202c",
  },
  {
    id: 75,
    name: "Bronze",
    primary: "#b8860b",
    secondary: "#8b6508",
    background: "#fffcf0",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#2d3748",
  },
  {
    id: 76,
    name: "Chrome",
    primary: "#a0aec0",
    secondary: "#718096",
    background: "#f7fafc",
    surface: "#ffffff",
    onPrimary: "#111827",
    onSurface: "#1a202c",
  },
  {
    id: 77,
    name: "Matte Black",
    primary: "#1a202c",
    secondary: "#000000",
    background: "#f7fafc",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1a202c",
  },
  {
    id: 78,
    name: "Titanium",
    primary: "#4a5568",
    secondary: "#2d3748",
    background: "#edf2f7",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1a202c",
  },
  {
    id: 79,
    name: "Copper",
    primary: "#b87333",
    secondary: "#a0522d",
    background: "#fff5ee",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1a202c",
  },
  {
    id: 80,
    name: "Iron",
    primary: "#4b5563",
    secondary: "#374151",
    background: "#f3f4f6",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#111827",
  },

  // 81-90: High Energy & Neon
  {
    id: 81,
    name: "Neon Lime",
    primary: "#4ade80",
    secondary: "#22c55e",
    background: "#f0fdf4",
    surface: "#ffffff",
    onPrimary: "#064e3b",
    onSurface: "#064e3b",
  },
  {
    id: 82,
    name: "Electric Blue",
    primary: "#38bdf8",
    secondary: "#0ea5e9",
    background: "#f0f9ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#0c4a6e",
  },
  {
    id: 83,
    name: "Shocking Pink",
    primary: "#f472b6",
    secondary: "#ec4899",
    background: "#fdf2f8",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#701140",
  },
  {
    id: 84,
    name: "Vivid Orange",
    primary: "#fb923c",
    secondary: "#f97316",
    background: "#fff7ed",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#7c2d12",
  },
  {
    id: 85,
    name: "Laser Green",
    primary: "#86efac",
    secondary: "#4ade80",
    background: "#f0fdf4",
    surface: "#ffffff",
    onPrimary: "#064e3b",
    onSurface: "#064e3b",
  },
  {
    id: 86,
    name: "Cyber Yellow",
    primary: "#facc15",
    secondary: "#eab308",
    background: "#fefce8",
    surface: "#ffffff",
    onPrimary: "#422006",
    onSurface: "#422006",
  },
  {
    id: 87,
    name: "Digital Violet",
    primary: "#c084fc",
    secondary: "#a855f7",
    background: "#faf5ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#3b0764",
  },
  {
    id: 88,
    name: "Aqua Flash",
    primary: "#22d3ee",
    secondary: "#06b6d4",
    background: "#ecfeff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#083344",
  },
  {
    id: 89,
    name: "Atomic Tangerine",
    primary: "#fb7185",
    secondary: "#f43f5e",
    background: "#fff1f2",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#4c0519",
  },
  {
    id: 90,
    name: "Night Glow",
    primary: "#10b981",
    secondary: "#34d399",
    background: "#064e3b",
    surface: "#022c22",
    onPrimary: "#ffffff",
    onSurface: "#d1fae5",
  },

  // 91-100: Elegant & Professional Dark
  {
    id: 91,
    name: "Onyx Elegance",
    primary: "#111827",
    secondary: "#374151",
    background: "#ffffff",
    surface: "#f9fafb",
    onPrimary: "#ffffff",
    onSurface: "#111827",
  },
  {
    id: 92,
    name: "Royal Emerald",
    primary: "#064e3b",
    secondary: "#065f46",
    background: "#f0fdf4",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#064e3b",
  },
  {
    id: 93,
    name: "Deep Amethyst",
    primary: "#4c1d95",
    secondary: "#5b21b6",
    background: "#f5f3ff",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#1e1b4b",
  },
  {
    id: 94,
    name: "Professional Maroon",
    primary: "#7f1d1d",
    secondary: "#991b1b",
    background: "#fef2f2",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#450a0a",
  },
  {
    id: 95,
    name: "Shadow Blue",
    primary: "#1e293b",
    secondary: "#334155",
    background: "#f8fafc",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#0f172a",
  },
  {
    id: 96,
    name: "Midnight Teal",
    primary: "#134e4a",
    secondary: "#115e59",
    background: "#f0fdfa",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#134e4a",
  },
  {
    id: 97,
    name: "Dark Chocolate",
    primary: "#451a03",
    secondary: "#78350f",
    background: "#fffbeb",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#451a03",
  },
  {
    id: 98,
    name: "Eclipse",
    primary: "#020617",
    secondary: "#0f172a",
    background: "#f8fafc",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#020617",
  },
  {
    id: 99,
    name: "Deep Berry",
    primary: "#831843",
    secondary: "#9d174d",
    background: "#fdf2f8",
    surface: "#ffffff",
    onPrimary: "#ffffff",
    onSurface: "#500724",
  },
  {
    id: 100,
    name: "Obsidian",
    primary: "#000000",
    secondary: "#1a1a1a",
    background: "#ffffff",
    surface: "#f1f1f1",
    onPrimary: "#ffffff",
    onSurface: "#000000",
  },
];
